#!/bin/sh
# =============================================================================
# wifi-setup.sh — Template WiFi credentials from /boot/wifi.txt
# =============================================================================
# Reads a plain key=value config from the boot-resource FAT partition
# (mounted read-only at /boot) and generates a wpa_supplicant config at
# /etc/wpa_supplicant/wpa_supplicant-wlan0.conf.
#
# Called by pocketforge-wifi-setup.service (Type=oneshot, Before=
# wpa_supplicant@wlan0.service). Idempotent: re-running with the same
# wifi.txt produces the same output; re-running with a changed wifi.txt
# overwrites the old config.
#
# wifi.txt format (one key=value per line, # comments, blank lines ok):
#   SSID=MyNetwork
#   PSK=MyPassword
#   # Optional — defaults to WPA-PSK if omitted:
#   KEY_MGMT=WPA-PSK
#
# If wifi.txt is missing or does not contain both SSID and PSK, this
# script logs a warning and exits 0 (graceful degradation — wlan0 stays
# down but the device boots normally). wpa_supplicant@wlan0.service will
# fail to start (no config file) and systemd will not loop on it because
# the service is Type=simple, not Restart=always.
#
# bd: tsp-iuz.2.2
# =============================================================================
set -eu

WIFI_CONF="/boot/wifi.txt"
WPA_CONF="/etc/wpa_supplicant/wpa_supplicant-wlan0.conf"
WPA_DIR="$(dirname "${WPA_CONF}")"

log() { echo "[pocketforge-wifi] $*"; }

# --- read wifi.txt -----------------------------------------------------------
if [ ! -f "${WIFI_CONF}" ]; then
    log "WARN: ${WIFI_CONF} not found — WiFi will not be configured"
    exit 0
fi

SSID=""
PSK=""
KEY_MGMT=""

while IFS= read -r line || [ -n "$line" ]; do
    # Strip leading/trailing whitespace, skip comments and blank lines
    line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    case "$line" in
        ""|\#*) continue ;;
    esac

    key="${line%%=*}"
    val="${line#*=}"

    case "$key" in
        SSID)     SSID="$val" ;;
        PSK)      PSK="$val" ;;
        KEY_MGMT) KEY_MGMT="$val" ;;
        *)        log "WARN: unknown key '${key}' in ${WIFI_CONF} — ignored" ;;
    esac
done < "${WIFI_CONF}"

# --- validate ----------------------------------------------------------------
if [ -z "${SSID}" ]; then
    log "WARN: SSID not set in ${WIFI_CONF} — WiFi will not be configured"
    exit 0
fi

if [ -z "${PSK}" ]; then
    log "WARN: PSK not set in ${WIFI_CONF} — WiFi will not be configured"
    exit 0
fi

# Default key management if not specified
if [ -z "${KEY_MGMT}" ]; then
    KEY_MGMT="WPA-PSK"
fi

# --- template wpa_supplicant config ------------------------------------------
log "Generating ${WPA_CONF} (SSID=${SSID}, key_mgmt=${KEY_MGMT})"

mkdir -p "${WPA_DIR}"

cat > "${WPA_CONF}" << EOF
# Auto-generated by pocketforge wifi-setup.sh from /boot/wifi.txt
# Do not edit directly — edit /boot/wifi.txt instead and reboot.
ctrl_interface=/run/wpa_supplicant
update_config=0

network={
    ssid="${SSID}"
    psk="${PSK}"
    key_mgmt=${KEY_MGMT}
}
EOF

chmod 0600 "${WPA_CONF}"
log "WiFi config written successfully"
