#!/bin/sh
# =============================================================================
# wifi-setup.sh — Template WiFi credentials from /boot/wifi.txt
# =============================================================================
# Reads a plain key=value config from the boot-resource FAT partition
# (mounted read-only at /boot) and generates a wpa_supplicant config at
# /etc/wpa_supplicant/wpa_supplicant-wlan0.conf.
#
# Called by pocketforge-wifi-setup.service (Type=oneshot, Before=
# wpa_supplicant@wlan0.service). Idempotent: re-running with the same
# wifi.txt produces the same output; re-running with a changed wifi.txt
# overwrites the old config.
#
# wifi.txt format (one key=value per line, # comments, blank lines ok):
#   SSID=MyNetwork
#   PSK=MyPassword
#   # Optional — defaults to WPA-PSK if omitted:
#   KEY_MGMT=WPA-PSK
#
# If wifi.txt is missing or does not contain both SSID and PSK, this
# script logs a warning and exits 0 (graceful degradation — wlan0 stays
# down but the device boots normally). wpa_supplicant@wlan0.service will
# fail to start (no config file) and systemd will not loop on it because
# the service is Type=simple, not Restart=always.
#
# bd: tsp-iuz.2.2
# =============================================================================
set -eu

WIFI_CONF="/boot/wifi.txt"
WPA_CONF="/etc/wpa_supplicant/wpa_supplicant-wlan0.conf"
WPA_DIR="$(dirname "${WPA_CONF}")"

log() { echo "[pocketforge-wifi] $*"; }

# --- read wifi.txt -----------------------------------------------------------
if [ ! -f "${WIFI_CONF}" ]; then
    log "WARN: ${WIFI_CONF} not found — WiFi will not be configured"
    exit 0
fi

SSID=""
PSK=""
KEY_MGMT=""

while IFS= read -r line || [ -n "$line" ]; do
    # Strip leading/trailing whitespace, skip comments and blank lines
    line="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    case "$line" in
        ""|\#*) continue ;;
    esac

    key="${line%%=*}"
    val="${line#*=}"

    case "$key" in
        SSID)     SSID="$val" ;;
        PSK)      PSK="$val" ;;
        KEY_MGMT) KEY_MGMT="$val" ;;
        *)        log "WARN: unknown key '${key}' in ${WIFI_CONF} — ignored" ;;
    esac
done < "${WIFI_CONF}"

# --- validate ----------------------------------------------------------------
if [ -z "${SSID}" ]; then
    log "WARN: SSID not set in ${WIFI_CONF} — WiFi will not be configured"
    exit 0
fi

if [ -z "${PSK}" ]; then
    log "WARN: PSK not set in ${WIFI_CONF} — WiFi will not be configured"
    exit 0
fi

# --- roam profile (board-scoped) --------------------------------------------
# Roaming/scan policy is radio-specific, so it is selected per board. The
# DEFAULT is "xr829" (base A133 single-radio soft-MAC): userspace 802.11r
# FT-PSK + a channel-learning bgscan. The Smart Pro S / A523 fullmac AIC8800D80
# does roaming AND scanning in its own firmware and must NOT be handed userspace
# FT/bgscan (the vendor stock image associates cleanly with a plain WPA-PSK
# config on this radio); it opts into the "fullmac" profile by shipping
# /etc/pocketforge/wifi-roam.conf (written by boards/tsp-s/rootfs-customize.sh).
# Sourcing that optional file may set WIFI_ROAM_PROFILE — it is the ONLY
# board-specific input to this otherwise-shared script.
WIFI_ROAM_PROFILE="xr829"
if [ -r /etc/pocketforge/wifi-roam.conf ]; then
    . /etc/pocketforge/wifi-roam.conf
fi

# Default key management if not specified in wifi.txt — profile-dependent.
# xr829: list FT-PSK alongside WPA-PSK so wpa_supplicant uses 802.11r Fast BSS
# Transition when the AP advertises it and falls back to plain WPA-PSK otherwise
# (negotiated per-AP, safe on any network). fullmac: plain WPA-PSK only.
if [ -z "${KEY_MGMT}" ]; then
    case "${WIFI_ROAM_PROFILE}" in
        fullmac) KEY_MGMT="WPA-PSK" ;;
        *)       KEY_MGMT="WPA-PSK FT-PSK" ;;
    esac
fi

# --- template wpa_supplicant config ------------------------------------------
mkdir -p "${WPA_DIR}"

case "${WIFI_ROAM_PROFILE}" in
fullmac)
    # fullmac profile (AIC8800D80 / A523): minimal WPA-PSK, no userspace bgscan
    # or FT. The chip firmware owns roaming/scanning, and this mirrors the vendor
    # stock config proven to associate on this radio. ctrl_interface is kept so
    # wpa_cli / health probes work.
    log "Generating ${WPA_CONF} (SSID=${SSID}, key_mgmt=${KEY_MGMT}, profile=fullmac)"
    cat > "${WPA_CONF}" << EOF
# Auto-generated by pocketforge wifi-setup.sh from /boot/wifi.txt
# Do not edit directly — edit /boot/wifi.txt instead and reboot.
# Profile: fullmac (AIC8800D80 / A523) — roaming + scanning are done in the chip
# firmware, so this is a minimal WPA-PSK config with no userspace bgscan/FT
# (matches the vendor stock config, which associates cleanly on this radio).
ctrl_interface=/run/wpa_supplicant
update_config=0

network={
    ssid="${SSID}"
    psk="${PSK}"
    key_mgmt=${KEY_MGMT}
}
EOF
    ;;
*)
    # --- roaming policy: xr829 (base A133 soft-MAC) (tsp-008) ----------------
    # The base unit's XR829 is a single-radio soft-MAC whose foreground scan is
    # NON-split, so each scan briefly stalls the associated link (and is the state
    # its firmware is most fragile in). We therefore roam CONSERVATIVELY — only when
    # the link is already weak — using the channel-LEARNING bgscan so a background
    # scan touches just this network's channels (~3-5) instead of all ~25+. The
    # firmware-offloaded CQM RSSI events drive the trigger. 802.11v BSS-TM is honored
    # by default (wpa_supplicant is built with WNM), letting the AP hand us a roam
    # target with no scan at all. 802.11r FT-PSK is now also requested (key_mgmt
    # above): the xr829 is a soft-MAC and wpa_supplicant runs FT over-the-air via the
    # kernel's userspace-SME auth/assoc path, so an FT transition skips the 4-way
    # handshake and collapses the reassociation gap (tsp-rcb — under on-device
    # validation; falls back to a full reassoc on APs that don't advertise FT).
    # A near-dormant "don't scan during an active stream" profile is deferred to the
    # kiosk supervisor (tsp-rcb).
    # Tunables — learn:<short_s>:<signal_threshold_dBm>:<long_s>:<db>. The threshold
    # is set a touch high (-72) to compensate for the driver's laggy 16-sample RCPI
    # averaging. The DB self-learns at runtime, so this works on ANY user network
    # with no per-network configuration; it persists across reboots under /var/lib.
    BGSCAN_DB_DIR="/var/lib/wpa_supplicant"
    SSID_SAFE="$(printf '%s' "${SSID}" | tr -c 'A-Za-z0-9._-' '_')"
    BGSCAN_DB="${BGSCAN_DB_DIR}/bgscan-${SSID_SAFE}.db"
    mkdir -p "${BGSCAN_DB_DIR}"
    log "Generating ${WPA_CONF} (SSID=${SSID}, key_mgmt=${KEY_MGMT}, bgscan=learn)"
    cat > "${WPA_CONF}" << EOF
# Auto-generated by pocketforge wifi-setup.sh from /boot/wifi.txt
# Do not edit directly — edit /boot/wifi.txt instead and reboot.
ctrl_interface=/run/wpa_supplicant
update_config=0
# Keep BSSes seen in the table between our infrequent background scans, so a
# learned roam target isn't aged out before the next (rare) scan (tsp-008).
ap_scan=1
bss_expiration_age=300

network={
    ssid="${SSID}"
    psk="${PSK}"
    key_mgmt=${KEY_MGMT}
    # Channel-learning background scan: roam only when the link is weak, with
    # scans narrowed to this network's channels. Self-learns; works on any net.
    bgscan="learn:45:-72:600:${BGSCAN_DB}"
}
EOF
    ;;
esac

chmod 0600 "${WPA_CONF}"
log "WiFi config written successfully (profile=${WIFI_ROAM_PROFILE})"
